---
'data':
  'max_pow' : 16 # Data should be in range of [2, ...2**max_pow]. How long the decode sequence should be
  'data_loc' : './data/2^16.json' # Path to data file. Either folder and will auto use the one with the largest exponent formated as "2^x.json" OR a json file
  'base' : 2

'model_args':
  'embed_dim' : 64
  'num_encoder_layers' : 2
  'num_decoder_layers' : 2
  'dim_feedforward' : 64
  'dropout' : .1
  'shared_embeddings' : True
  'scale_embeddings' : False
  'learn_positional_encoding' : False
  'max_decode_size' : 64

'optimizer':
  'type' : 'adam'
  'opt_args' : 
    'lr' : 0.001
  'max_grad_norm' : 1
  'gradient_accumulation_steps' : 8

'scheduler' : 
  'type' : linear_schedule_with_warmup
  'n_warmup_steps' : 10
  'nb_epochs' : 1

'loader' :
  'train' : 
    'batch_size' : 64
    'shuffle' : True
  'test' : 
    'batch_size' : 256
    'shuffle' : False

'io':
  'save_path' : './models/new_training/'
  'checkpoint_every' : 80
  'evaluate_every' : 1
  'evaluate_final' : True

'metrics' : 
  'n_beams' : 2
  'max_num' : 100
  'save_suffix' : ''
  'temperature' : 1.0

'verbose' : True