'data':
  'train_path' : 'data/train_data_2^13.npy'
  'test_path' : 'data/test_data_2^13.npy'
  'base' : 30

'model_args':
  'embed_dim' : 128
  'num_encoder_layers' : 6
  'num_decoder_layers' : 6
  'dim_feedforward' : 512
  'dropout' : .1
  'shared_embeddings' : True
  'scale_embeddings' : True
  'learn_positional_encoding' : False
  'max_decode_size' : 64
  'repeat_positional_encoding' : True
  'positional_encoding_query_key_only' : True
  'norm_first' : False

'optimizer':
  'type' : 'adam'
  'opt_args' : 
    'lr' : 0.001
  'max_grad_norm' : 1
  'gradient_accumulation_steps' : 1

'scheduler' : 
  'type' : linear_schedule_with_warmup
  'n_warmup_steps' : 2400
  'nb_epochs' : 50
  'max_steps' : -1

'loader' :
  'train' : 
    'batch_size' : 64
    'random_sampling' : True 
  'test' : 
    'batch_size' : 256
    'shuffle' : False

'io':
  'save_path' : './models/base_30_v6/'
  'checkpoint_every' : 1000
  'evaluate_every' : 1
  'evaluate_final' : True

'metrics' : 
  'n_beams' : 2
  'max_num' : -1
  'save_suffix' : ''
  'temperature' : 1.0

'multi_gpu' : 'auto'
'verbose' : True

'wandb' : 
  'enabled' : False
  'project' : 'integer-factorization'
  'entity' : 'sims-s'
  'watch_args' : 
    'log' : 'all'
    'log_freq' : 50


