data:
  base: 2
  data_loc: ./data/2^16.json
  input_padding: pad
  max_decode_size: 49
  max_input_size: 18
  max_pow: 16
io:
  save_path: ./models/base_2/
loader:
  test:
    batch_size: 256
    shuffle: false
  train:
    batch_size: 64
    shuffle: true
metrics:
  max_num: -1
  n_beams: 2
  save_suffix: ''
model_args:
  dim_feedforward: 128
  dropout: 0.1
  embed_dim: 64
  learn_positional_encoding: false
  num_decoder_layers: 4
  num_encoder_layers: 4
  scale_embeddings: false
  shared_embeddings: true
optimizer:
  max_grad_norm: 1
  opt_args:
    lr: 0.001
  type: adam
scheduler:
  n_warmup_steps: 2000
  nb_epochs: 50
  nb_steps: 41050
  type: linear_schedule_with_warmup
tokenizer:
  n_tokens: 6
  pad_token_id: 3
verbose: true
